### ISSUE TITLE
Server crash on 7.8.8

### ISSUE THREAD

**Issue by Stargateur** [inlife/eco-no-player-credits#2]
Don't work for 7.8.8 in standalone + this mod. As you update the mod for 8.0.X, seem that both version are not compatible.

**Comment by inlife** [comment]
well yes, the new version for 8.x.x isn't compatible with 7.x.x, and there is not much i can do about it
just download the binaries of older version

https://eco-mods.com/resources/no-player-credits.120/history

**Comment by Stargateur** [comment]
Thanks didn't find the link for past version
